apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm-fastapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/guilhermemaas/foundation-platform-demos
    targetRevision: HEAD
    path: argocd-helm-fastapi/helm-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: foundation-platform-demos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true