apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-fastapi-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/guilhermemaas/foundation-platform-demos/argocd-helm-flask'
    targetRevision: HEAD
    path: helm-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 