replicaCount: 2

image:
  repository: minha-registry/minha-app-vite
  tag: latest
  pullPolicy: IfNotPresent

environment: "DEV"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: vite.dev.local   # <- DNS configurável
      paths:
        - path: /
          pathType: Prefix
  tls: [] # Adicione se quiser usar HTTPS