version: "3.9"

services:
  db:
    image: postgres:13-alpine
    container_name: zabbix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      # ajusta conforme seu fuso
      ZBX_TIMEZONE: America/Sao_Paulo
    volumes:
      # para scripts de alerta customizados ou módulos externos
      - zbx_server_scripts:/usr/lib/zabbix/alertscripts
      - zbx_server_modules:/usr/lib/zabbix/modules

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-frontend
    restart: unless-stopped
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    environment:
      # conexão com o banco
      DB_SERVER_HOST: db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      # aponta para o servidor Zabbix
      ZBX_SERVER_HOST: zabbix-server
      # timezone do PHP
      PHP_TZ: America/Sao_Paulo
    volumes:
      - zbx_web_modules:/usr/lib/zabbix/modules

volumes:
  pgdata:
  zbx_server_scripts:
  zbx_server_modules:
  zbx_web_modules:
