apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fast-api-hello.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fast-api-hello.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fast-api-hello.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: NAME
              value: {{ .Values.env.name }} 