apiVersion: v1
kind: Service
metadata:
  name: {{ include "fast-api-hello.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "fast-api-hello.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: ClusterIP